model:
  in_channels: 3
  base_channels: 64
  channel_mults:
  - 1
  - 2
  - 4
  - 8
  num_res_blocks: 2
  attention_resolutions:
  - 16
  - 8
  dropout: 0.1
  style_dim: 512
style_encoder:
  style_dim: 512
  style_layers:
  - 3
  - 8
  - 17
  - 26
  content_layers:
  - 17
diffusion:
  num_timesteps: 1000
  beta_schedule: cosine
