mode: real
real_root_dir: "/content/drive/MyDrive/Năm 3 kì 2/TH DL/project/AdaIn/2_data/processed"
split: train
style_domain: anime
image_size: 256

batch_size: 4
num_workers: 2
shuffle: true

lr: 0.0001
lambda_style: 10.0
epochs: 50
log_every: 10

save_dir: "/content/drive/MyDrive/Năm 3 kì 2/TH DL/project/AdaIn/checkpoints"

seed: 42

early_stopping: true
rise_patience: 3