mode: real
real_root_dir: 'E:/Nam3_ki2/TH DL/PROJECT/23KDL_Deep_learning/data/processed'
split: train
style_domain: sketch
image_size: 256

batch_size: 2
num_workers: 0
shuffle: true

lr: 0.0001

lambda_mse: 10.0
lambda_l1: 0.5
lambda_tv: 1.0e-5

epochs: 50
log_every: 10

save_dir: 'E:/Nam3_ki2/TH DL/PROJECT/23KDL_Deep_learning/adain-baseline/checkpoints'

seed: 42

early_stopping: true
rise_patience: 3